# File: environment.yml
# Created Date: Saturday February 13th 2021
# Author: Steven Atkinson (steven@atkinson.mn)

name: nam
channels:
  - pytorch
dependencies:
  - black
  - flake8
  - h5py
  - jupyter
  - matplotlib
  - numpy
  - pip
  - pytest
  - pytorch
  - scipy
  - semver
  - tensorboard
  - tqdm
  - wheel
  - pip:
      - onnx
      - onnxruntime
      - pre-commit
      - pytorch_lightning
      - sounddevice
      - wavio
      - -e .
